### ISSUE TITLE
Upload the jar files

### ISSUE THREAD

**Issue by MrDiamond123** [Bitterholz/LP2#19]
When your done with a 'update' can you please upload the mod file as a release? It takes too long to build mods on my computer!

**Comment by DAmNRelentless** [comment]
Why shouldn't they? I guess when this gets any stable playable version in the future, they'll release it on curseforge or something. Never seen someone who just published the source so the users had to build the jar themself.

**Comment by Bitterholz** [comment]
This mod is very much NOT ready for use! @MrDiamond123. There is really no point at this time for you to fiddle with building or anything, unless you have code to contribute. And even then you dont need any JAR's.

Once we think a playable version has been reached, we will release a alpha for people to test and (hopefully not) break. Until then, Its pointless to compile this.

This issue is hereby closed.
