### ISSUE TITLE
For what version will be this available and when?

### ISSUE THREAD

**Issue by Roman-Simik** [Bitterholz/LP2#23]
Title says it all

**Comment by SonOfTheStars** [comment]
I am unable to give a release date. Please do not ask for ETAs, It will be out when I deem it ready. No offense.

**Comment by loordgek** [comment]
will we skip 1.12

**Comment by Roman-Simik** [comment]
yeah, thanks for the Info, but this is really game changing mod which makes a storage network so easy, it works like in real-life and doesn't need any new functions. It's really heart-breaking that you are not able to atleast port the 1.7.10 version to the 1.12 (it could be like 1 day work i think, since you have already pull request from other guys that managed to port it to 1.12). And then you could continue doing the completely new version of the mod with new functions,... but even with that, thanks for all the work you're doing on this mod.

**Comment by rlnt** [comment]
Porting a mod from 1.7.10 to 1.12 isn't only taking one day. Obviously you have no coding knowledge if you say that. Many things have changed since 1.7.10 and the pull request is not a port to the 1.12. It's more some code adjustments to make the current code snippets they have compatible to the 1.12 version. Porting a mod from 1.7.10 would be silly, it's more efficent to recode it.
